### ISSUE TITLE
README improvement ideas

### ISSUE THREAD

**Issue by hectorfhurtado** [brandlabs/bigcommerce-custom-fields-hierarchy#3]
When started using this package I struggle with these because I could not get the information from the README or it was not commented. I think these can improve the project if added:

- How to npm install section (it seems obvious but wasn't at the moment :) ).
- Clarifying delimiter is just not a slash, it is in fact ` \ ` (SPACE followed by SLASH followed by SPACE).
- You need to inject the products array on your template (like on product-view template I used `{{inject 'product' product}}`).

**Comment by shotaK** [comment]
Thanks, yes it definitely needs to be updated based on the new standards.
